contracts/mocks/protocol/integration/lib/CompoundMock.sol, contracts/protocol/integration/CompoundWrapAdapter.sol, contracts/protocol/integration/lib/Compound.sol, test/integration/compoundWrapModule.spec.ts, test/protocol/integration/compoundWrapAdapter.spec.ts, test/protocol/integration/lib/compound.spec.ts, test/protocol/modules/compoundLeverageModule.spec.ts, test/protocol/modules/compoundLeverageModule2.spec.ts
README Checks
Code Checks
- [] Add explanatory comments. If there is complex code that requires specific context or understanding, note that in a comment
- [] Remove unncessary comments. Any comments that do not add additional context, information, etc. should be removed
- [] Add javadocs. 
- [] Scrub through the code for inconsistencies …
=> report all

test/integration/compoundWrapModule.spec.ts, test/protocol/integration/compoundWrapAdapter.spec.ts
Updates `CompoundWrapModule` spec to use library link logic implemented in #60.
(Fixes CI)
=> Fix failing CompoundWrap tests

utils/common/addressUtils.ts, utils/common/index.ts, utils/fixtures/aaveFixture.ts, utils/test/accountUtils.ts, utils/test/index.ts
This should fix an issue `set.js` ran into where `getRandomAddress` relied on Hardhat  and messed up downstream imports from `utils/fixtures` if any files in that folder tried to use the method.  
The fixtures are need to be Hardhat-free and cannot import anything from `utils/test`.
=> Move getRandomAddress (w/out hardhat) to utils/common

contracts/protocol/modules/GeneralIndexModule.sol
README Checks
Code Checks
- [] Add explanatory comments. If there is complex code that requires specific context or understanding, note that in a comment
- [] Remove unncessary comments. Any comments that do not add additional context, information, etc. should be removed
- [] Add javadocs. 
- [] Scrub through the code for inconsistencies …
=> Updated javadocs for GeneralIndexModule.

contracts/protocol/integration/UniswapV2TransferFeeExchangeAdapter.sol, test/protocol/integration/uniswapV2TransferFeeExchangeAdapter.spec.ts, test/protocol/modules/tradeModule.spec.ts, utils/contracts/index.ts, utils/deploys/deployAdapters.ts
README Checks
Code Checks
- [] Add explanatory comments. If there is complex code that requires specific context or understanding, note that in a comment
- [] Remove unncessary comments. Any comments that do not add additional context, information, etc. should be removed
- [] Add javadocs. 
- [] Scrub through the code for inconsistencies …
=> Add new Uniswap transfer fee adapter

contracts/protocol/integration/exchange/BalancerV1ExchangeAdapter.sol, contracts/protocol/integration/exchange/UniswapV2ExchangeAdapterV2.sol, test/protocol/integration/balancerV1ExchangeAdapter.spec.ts, test/protocol/integration/uniswapV2ExchangeAdapterV2.spec.ts, utils/deploys/deployAdapters.ts
- Add tests for `BalancerV1ExchangeAdapter`
- Refactor tests for `UniswapV2ExchangeAdapterV2`
=> Add BalancerV1ExchangeAdapter tests

contracts/protocol/modules/GeneralIndexModule.sol, package-lock.json, package.json, test/protocol/modules/generalIndexModule.spec.ts
**Review Fixes Summary** 
+ **Note**: Even though external positions are not allowed during rebalance instantiation, external positions can be added during the rebalance itself. 
+ cbcd4d9: Check added to the trade parameter validation method
+ **Line 198**: If we expect this to be reused, consider moving this require into the Position.sol library
+ cbcd4d9: uses Position's `hasExternalPosition` helper in the `require`
+ **Line 245**: nit - add linebreak
+ 95c6809
+ **nit**: Consider moving the lowest level functions  to the bottom of the file 
+ 95c6809: internal functions re-ordered
+ **[Line 204][3]**: Instead of emitting an event per component, what would the advantage / disadvantage be of emitting a  a single event?
> [Chris]:  Uncertain about this...
> [Brian/Felix] (from meeting), …
=> Final review fixes for GeneralIndexModule

contracts/protocol/integration/wrap/KyberMigrationAdapter.sol, external/abi/kyber/KyberNetworkTokenV2.json, external/contracts/kyber/KyberNetworkTokenV2.sol, package-lock.json, package.json, test/protocol/integration/wrap/kyberMigrationWrapAdapter.spec.ts, utils/contracts/index.ts, utils/contracts/kyber.ts, utils/deploys/deployAdapters.ts, utils/deploys/deployExternal.ts, yarn.lock
Add KNC Migration Wrap Adapter to facilitate migration from Legacy KNC tokens to new KNC tokens held within DPI.
KNC Token Migration Guide: https://blog.kyber.network/knc-token-migration-guide-fda08bfe62c2
Old KNC token contract: https://etherscan.io/token/0xdd974d5c2e2928dea5f71b9825b8b646686bd200
New KNC token contract: https://etherscan.io/token/0xdeFA4e8a7bcBA345F687a2f1456F5Edd9CE97202
Migration ratio: 1:1 (1 old KNC will be migrated to 1 new ERC-20 KNC token)
Method to be used for migration: [`mintWithOldKnc(uint256)`](https://github.com/KyberNetwork/kyber_protocol_sc/blob/4a3a961ee8c8f121cc8b48bf220daa849172275a/contracts/sol6/token/KyberNetworkTokenV2.sol#L46)
=> KNC Migration Adapter

contracts/interfaces/external/IComptroller.sol, contracts/mocks/StandardTokenMock.sol, contracts/mocks/external/ComptrollerMock.sol, contracts/protocol/integration/claim/CompClaimAdapter.sol, test/integration/claim/compClaimAdapter.spec.ts, utils/contracts/index.ts, utils/deploys/deployAdapters.ts
This is a simple claim adapter that allows managers to claim COMP from assets deposited on Compound.
It's interfacing with Comptroller and conforms to the IClaimAdapter interface used by the Set Protocol V2 ClaimModule.
Tests are using mocked Comptroller contract and are limited to ClaimAdapter <> ClaimModule integration.
=> Adding CompClaimAdapter

contracts/mocks/external/ZeroExMock.sol, contracts/protocol/integration/exchange/ZeroExApiAdapter.sol, package.json, test/protocol/integration/exchange/zeroExApiAdapter.spec.ts, yarn.lock
We are looking to deploy a new VIP source for Uniswap V3 (pending [ZEIP-88](https://0x.org/zrx/vote/zeip-88) vote). This updates the `ZeroExApiAdapter` to support this new source.
Code Checks
Broader Considerations
=> feat: update ZeroExApiAdapter to support Uniswap V3 VIP source

contracts/protocol/integration/exchange/ZeroExApiAdapter.sol, test/protocol/integration/exchange/zeroExApiAdapter.spec.ts, test/protocol/modules/tradeModule.spec.ts, utils/deploys/deployAdapters.ts
- Allow any destination address if a null recipient is found in liquidity provider and uniswap v3 calldata.
- Check for prescence of WETH token in paths for uniswap v3 in ETH selling/buying calldata.
- Pretty sure you guys don't use ETH but might as well include it for completeness.
README Checks
Code Checks
- [] Add explanatory comments. …
=> ZeroExAdapter null recipient fix

package.json, utils/fixtures/uniswapV3Fixture.ts, utils/test/index.ts
Some imports from the Uniswap V3 fixture caused the repo to compile fine when running standalone but failed when running as a library.
=> Fix broken imports

contracts/product/AMMSplitter.sol
README Checks
Code Checks
- [] Add explanatory comments. If there is complex code that requires specific context or understanding, note that in a comment
- [] Remove unncessary comments. Any comments that do not add additional context, information, etc. should be removed
- [] Add javadocs. 
- [] Scrub through the code for inconsistencies …
=> Fix Felix internal audit comments

contracts/protocol/integration/index-exchange/UniswapV2IndexExchangeAdapter.sol, test/integration/uniswapV2ExchangeGeneralIndexModule.spec.ts, test/protocol/integration/index-exchange/uniswapV2IndexExchangeAdapter.spec.ts
Currently, all index exchange adapters only support single hop trades. With the addition of Badger to the DPI, we will need to execute two-hop trade when rebalancing, since Badger is most liquid with wBTC.
Update `UniswapV2IndexExchangeAdapter` to support multi-hop trades. The Badger token is most liquid on Sushiswap, so this adapter will be sufficient to fill our needs.
- In `getTradeCalldata` check if the _data parameter is empty. If so, create the trade path using the input and output tokens (single-hop trade)
- If _data is not empty, then interpret it as a single address. This address will be the intermediate token of the two-hop trade
- For `GeneralIndexModule` to perform a two-hop trade, ensure that you use `setExchangeData` beforehand to encode the intermediate token
=> Update UniswapV2IndexExchangeAdapter to support two-hop trades

contracts/interfaces/IClaimAdapter.sol, contracts/mocks/external/ComptrollerMock.sol, contracts/mocks/integrations/ClaimAdapterMock.sol, contracts/protocol/integration/claim/CompClaimAdapter.sol, contracts/protocol/modules/ClaimModule.sol, test/integration/claim/compClaimAdapter.spec.ts, test/protocol/modules/claimModule.spec.ts
=> ClaimModule Audit fixes

contracts/interfaces/external/ICErc20.sol, contracts/interfaces/external/ICEth.sol, contracts/interfaces/external/IComptroller.sol, contracts/interfaces/external/IUniswapV2Factory.sol, contracts/interfaces/external/IWETH.sol, contracts/mocks/AddressArrayUtilsMock.sol, contracts/mocks/external/ComptrollerMock.sol, contracts/mocks/external/SynthetixExchangerMock.sol, contracts/mocks/integrations/StakingAdapterMock.sol, contracts/mocks/integrations/WrapAdapterMock.sol, contracts/mocks/protocol/CustomSetValuerMock.sol, contracts/mocks/protocol/module/DebtModuleMock.sol, contracts/protocol-viewers/ERC20Viewer.sol, contracts/protocol/integration/exchange/UniswapV2ExchangeAdapterV2.sol, contracts/protocol/integration/governance/AaveGovernanceAdapter.sol, contracts/protocol/integration/governance/AaveGovernanceV2Adapter.sol, contracts/protocol/integration/index-exchange/UniswapV3IndexExchangeAdapter.sol, contracts/protocol/integration/oracles/CTokenOracle.sol, contracts/protocol/integration/oracles/YearnVaultOracle.sol, contracts/protocol/integration/staking/CurveStakingAdapter.sol, contracts/protocol/integration/wrap/AaveMigrationWrapAdapter.sol, contracts/protocol/integration/wrap/CompoundWrapAdapter.sol, contracts/protocol/integration/wrap/YearnWrapAdapter.sol, contracts/protocol/modules/CompoundLeverageModule.sol, contracts/protocol/modules/CustomOracleNAVIssuanceModule.sol, contracts/protocol/modules/NAVIssuanceModule.sol, external/contracts/uniswap/v2/lib/UniswapV2Library.sol, external/contracts/yearn/BaseStrategy.sol
Preliminary step for upgrading Solidity at some point in the future. It's common for warnings to become errors at the solc version increases. 
Removes a few dozen warnings, in 3 categories. 
+ Missing SPDX license id 
+ state mutability can be restricted to pure or view (mostly in mocks and adapters)
+ unused parameters
Only changes that touch logic are in 
+ 788d040 where a `NavIssuance` module internal method has an unused parameter
+ 34e6e76 where an unused local variable assignment is made in `CompoundLeverageModule`
(Also removed a lot of trailing whitespace here ... there's a bit of noise in the diff unfortunately)
=> Fix Solidity warnings

test/integration/aaveUniswapLeverageDebtIssuance.spec.ts
=> ALM integration tests

README.md
According to the pinned message in the Telegram group, Telegram is deprecated in favor of Discord
=> Replace Telegram link with Discord

package.json
Updating version a full (minor) step because this release has breaking changes for anyone consuming the typechain artifacts. 
They're now generated using `@typechain/hardhat` and support the latest ethers (5.4.6)
To import ambient type definitions (.d.ts) from this package you must now pull directly from the typechain folder external to `dist`, e.g
```ts
import { Controller } from "@setprotocol/set-protocol-v2/typechain"
```
Factories are still transpiled to JS in the `dist` though.
=> Publish 0.1.0

hardhat.config.ts
In set-protocol-v2, before each block times out occasionally
- [Test run, 8 days ago](https://app.circleci.com/pipelines/github/SetProtocol/set-protocol-v2/819/workflows/a4aa141d-f393-4443-baf1-211a3719d1c2/jobs/3162)
- [Coverage run, 3 days ago](https://app.circleci.com/pipelines/github/SetProtocol/set-protocol-v2/841/workflows/0f7f59a2-24cd-4f15-9ec5-40faf7d4f247/jobs/3260)
```
1) AaveUniswapLeverageDebtIssuance
"before each" hook for "should not update the collateral position on the SetToken":
Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/circleci/set-protocol-v2/test/integration/aaveUniswapLeverageDebtIssuance.spec.ts)
at listOnTimeout (internal/timers.js:549:17)
at processTimers …
```
=> Increase tests timeout

README.md, package.json, tsconfig.json
When you install `@setprotocol/set-protocol-v2` from npm, the fixtures etc are currently unusable because TS throws errors like this:
```
test/manager/baseManagerV2.spec.ts:23:31 - error TS7016: Could not find a declaration file for module '@setprotocol/set-protocol-v2/dist/utils/fixtures/PerpV2Fixture'. '/Users/cgewecke/code/set/set-v2-strategies/node_modules/@setprotocol/set-protocol-v2/dist/utils/fixtures/PerpV2Fixture.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/setprotocol__set-protocol-v2` if it exists or add a new declaration (.d.ts) file containing `declare module '@setprotocol/set-protocol-v2/dist/utils/fixtures/PerpV2Fixture';`
23 import { PerpV2Fixture } from "@setprotocol/set-protocol-v2/dist/utils/fixtures/PerpV2Fixture"; …
```
=> Fix dist package for typescript

contracts/interfaces/IModuleIssuanceHookV2.sol, contracts/protocol/modules/PerpV2LeverageModule.sol, contracts/protocol/modules/SlippageIssuanceModule.sol, package.json, test/integration/perpV2LeverageSlippageIssuance.spec.ts, test/protocol/modules/slippageIssuanceModule.spec.ts, tsconfig.json
`getComponent...Units` methods throw when used with the PerpV2LeverageModule because its issuance and redemption adjustments getters are non-view. They simulate trades on UniswapV3 and revert in order to discover swap outcomes and can only be called off-chain via methods like `ethers.callStatic`
Have made the smallest intervention possible here, renaming the getters to reflect their intended use context and adding / updating tests. 
**Open Questions**
+ Should this PR also override the inherited getters and revert (to prevent incorrect use of those methods)
+ Or ... should we change the state-mutability signature for these methods across the inheritance chain (instead just of renaming and changing SlippageIssuance's)
=> Make SlippageIssuanceModule issuance & redemption component units getters non-view

contracts/protocol/modules/PerpV2LeverageModule.sol, test/integration/perpV2LeverageSlippageIssuance.spec.ts
Context for this change is Iosiro's audit item (item 5.12: Invalid state after liquidation) about scenarios where the token is insolvent, e.g has 
+ positive collateral balance
+ no positions open
+ a negative owedRealizedPnl greater than the collateral balance
They note:
> It was possible to have a negative account balance after liquidation. Users attempting to redeem tokens would transfer collateral into an untracked default position, while issuance would result in a revert due to the SetToken not having any collateral available.
> In the context of a SetToken, it would be best for users to not have to repay the outstanding debt and instead be allowed to redeem any remaining assets kept in other external positions or as default positions. This would require removal of the module and …
=> Ensure returned accountValueIssued never negative in  #_executePositionTrades

contracts/interfaces/IPerpV2LeverageModule.sol, contracts/lib/PreciseUnitMath.sol, contracts/mocks/PreciseUnitMathMock.sol, contracts/protocol/modules/PerpV2LeverageModule.sol, package.json, test/lib/preciseUnitMath.spec.ts, test/protocol/modules/perpV2LeverageModule.spec.ts
https://docs.google.com/spreadsheets/d/1-S4Gkn5UD5MsZcODgCHCOBY9UX8bETPEk7jzzvwxsYY/edit#gid=0
=> PerpV2LeverageModule ABDK audit fixes

contracts/lib/PreciseUnitMath.sol, utils/common/mathUtils.ts
There's a bug in current version:
```solidity
function preciseDivCeil(int256 a, int256 b) internal pure returns (int256) {
require(b != 0, "Cant divide by 0");
a = a.mul(PRECISE_UNIT_INT);
int256 c = a.div(b);
if (c * b != a) {
c = c > 0 ? c + 1 : c - 1;
}
return c;
}
```
For example: when a is 1, b is 1000000000000000000000, preciseDivCei should return 1. But in function preciseDivCeil, the value  of  c = a.div(b) is 0, and since c * b != a is true, c > 0 is false, then c = c - 1 = -1, which is not right!
=> fix bug in function preciseDivCeil

utils/fixtures/aaveV2Fixture.ts
should add keyword `await` before `this.lendingRateOracle.setMarketBorrowRate(asset, rate);`
```js
public async setMarketBorrowRate(asset: Address, rate: BigNumberish): Promise<void> {
this.lendingRateOracle.setMarketBorrowRate(asset, rate);
}
```
=> fix bug in function setMarketBorrowRate of class AaveV2Fixture

package.json
Somehow the `initialize` method in typechain factory for IssuanceModule was corrupted in 0.1.14. It only contains types for two parameters (and should have 6) 
```js
{
inputs: [
{
internalType: "contract ISetToken",
name: "_setToken",
type: "address",
},
{
internalType: "contract IManagerIssuanceHook",
name: "_preIssueHook",
type: "address",
},
],
name: "initialize",
outputs: [],
stateMutability: "nonpayable",
type: "function",
},
```
=> Rebuild and publish 0.1.15

contracts/mocks/external/ZeroExMock.sol, contracts/protocol/integration/exchange/ZeroExApiAdapter.sol, hardhat.config.ts, test/protocol/integration/exchange/zeroExApiAdapter.spec.ts
Adds new direct RFQ fill methods to ZeroExApiAdapter. Also removes deprecated ones.
=> feat: add direct RFQT fill suport to ZeroExApiAdapter [SIM-230]

subgraph/test/deploy-state-multi-token.ts, subgraph/test/deploy-state.ts
Local Hardhat node state deployment scripts for subgraph development and testing have been migrated from the set-protocol-v2-subgraph repo to a new `subgraph/test/` directory in this repo, as these scripts are dependent on a Hardhat chain deployment from this repo.
=> fix(tests): Add Hardhat deployment subgraph test scripts 

contracts/protocol/modules/v2/PerpV2LeverageModuleV2.sol, test/integration/perpV2BasisTradingSlippageIssuance.spec.ts, test/integration/perpV2LeverageV2SlippageIssuance.spec.ts, test/protocol/modules/v2/perpV2BasisTradingModule.spec.ts, test/protocol/modules/v2/perpV2LeverageModuleV2.spec.ts, utils/common/perpV2Utils.ts
@0xSachinK Here are couple loose ends as discussed in Slack 
+ [Add fix for _updateExternalPositionUnit](https://github.com/SetProtocol/set-protocol-v2/commit/a6b3cfcb487ed4e9ab74275a0dbd2119c105c446)
+ [Add test for negative balance check in _calculateNetFeesPositionUnit](https://github.com/SetProtocol/set-protocol-v2/commit/5e42adc0fb1ad67c01584b020f34cb70d20bfb34)
=> fix(tests): Small fixes for BasisTradingModule audit changes

contracts/interfaces/external/perp-v2/IAccountBalance.sol, contracts/protocol/lib/PositionV2.sol, contracts/protocol/modules/v2/PerpV2BasisTradingModule.sol, contracts/protocol/modules/v2/PerpV2LeverageModuleV2.sol, deprecated/PerpV2LeverageModule.sol, test/integration/perpV2BasisTradingSlippageIssuance.spec.ts, test/integration/perpV2LeverageV2SlippageIssuance.spec.ts, test/protocol/modules/v2/perpV2BasisTradingModule.spec.ts, test/protocol/modules/v2/perpV2LeverageModuleV2.spec.ts, utils/common/perpV2Utils.ts, utils/deploys/deployAdapters.ts
I was not able to recreate the bug even after depositing the entire withdrawn amount for >500 times consecutively. But as bernard pointed out in our chat, he was able to recreate the issue without any withdrawing and just `depositing airdropped tokens`.
In this [script](https://gist.github.com/bernard-wagner/a1e8783404256a898e4df66d2b0a83ed) that bernard shared, he 
- creates a SetToken with 100 USDC as a position unit. 
- Issues 10 such Sets. 
- Then airdrops 100 USDC to the Set. 
- Then calls deposit with (balance/totalSupply = 1100/10 = 110) units.
- In the deposit function, we calculate `depositNotional = 110 * totalsupply = 100 * 10 = 1100`, and then invoke deposit on PerpV2, which pulls 1100 USDC from the Set.
- But, here the `deposit` function should have reverted because we are …
=> fix(PerpV2BasisTradingModule): External audit fixes for low-risk findings and Internal audit fixes

contracts/protocol/modules/v2/PerpV2BasisTradingModule.sol, test/protocol/modules/v2/perpV2BasisTradingModule.spec.ts
This getter would be consumed by the basis trading strategy extension contract to determine the amount that is available to be reinvested.
=> fix(PerpV2BasisTradingModule): Expose getter to fetch updated settled funding

contracts/protocol/modules/v2/PerpV2LeverageModuleV2.sol, test/integration/perpV2BasisTradingSlippageIssuance.spec.ts, test/integration/perpV2LeverageV2SlippageIssuance.spec.ts, test/protocol/modules/v2/perpV2LeverageModuleV2.spec.ts
In this [transaction](https://optimistic.etherscan.io/tx/0x423c23252f271bfb4b2004abd0d1a88acc9cbaec592c31684c0476aa66aa543f), rebalance fails because, (quoting @bweick from slack)
```
nvm so basically there 1.005 Sets we try to withdraw 13159 per Set which would calculate to 13224.795 
which is rounded down to 13224 so that's the amount we get back from Perp
When we then go to make a position out of it 13224/1.005 = 13158.20 so rounded down to 13158
And then we try to trade 13159
```
=> fix(PerpV2LeverageModuleV2): Round up during withdraw

contracts/protocol/modules/v1/SlippageIssuanceModule.sol, package.json, test/integration/perpV2BasisTradingSlippageIssuance.spec.ts, test/integration/perpV2LeverageV2SlippageIssuance.spec.ts, test/protocol/modules/v1/slippageIssuanceModule.spec.ts
[Triage Basis Trading: Delta Neutrality Deviation Spike](https://docs.google.com/document/d/1_P38X6SvRq4WZ9Ys3npRLnhrxY5pM1s9ne9KWj4sq90/edit)
Virtual position units update during issuance and redemption.
Update calculations to
1. Ensure position units don't change due to issuance and redemption.
2. Ensure we aren't double charging fees in the new flow.
[Sheet explaining new calculations which fulfill the requirements](https://docs.google.com/spreadsheets/d/1cTMW1PacANYzf-oLkc_OFmSBDk9mZNLdA1GVQp0VEcQ/edit#gid=0)
=> fix(SlippageIssuanceModule): Fix issuance & redemption flows to not update position units
